language: objective-c
xcode_sdk: iphonesimulator
before_install:
    - brew update > /dev/null; if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
matrix:
    include:
        - xcode_workspace: SampleProject/SampleProject.xcworspace
          xcode_scheme: VOKCoreDataManager
        - xcode_workspace: Paging Data Source Example/Paging Data Source Example.xcworspace
          xcode_scheme: Paging Data Source Example
